# Generated by Django 4.0.6 on 2022-08-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tags_order_customer_order_name_order_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tags',
        ),
        migrations.AddField(
            model_name='products',
            name='tags',
            field=models.ManyToManyField(to='app.tags'),
        ),
    ]
